# Generated by Django 6.0.3 on 2026-04-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='time_survied',
            new_name='time_survived',
        ),
    ]
