# Generated by Django 6.0.3 on 2026-04-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_time_survied_gamesession_time_survived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='played_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
